# Workflow Code: CosmicFalcon_v1   DO NOT REMOVE
# Purpose:
#    Runs Selenium C# tests in GitHub Actions on a schedule.
#
# Frequency:
#    - Workflow template for running Selenium tests on a schedule. This workflow supports the UI Health Check feature
#
# Projects to use this Template with:
#    - Testing projects that use Selenium C#.
#
# TODO Prerequisites:
#    - Add Application Insights secret (APPLICATIONINSIGHTS_CONNECTION_STRING) to every environment you are testing.
#    - Update your Selenium solution to export test results to Application Insights using the IM.ExportToAppInsights NuGet package. 
#      Detailed setup guidance can be found here: https://github.com/im-practices/techhub/blob/main/docs/Azure/content/Health-Checks/Selenium-UI-Health-Check.md

name: 🧪 Scheduled Selenium C# Tests
run-name: 🧪 Run Scheduled Selenium C# Tests

on:
  workflow_dispatch:
  schedule: # TODO: Update the schedule to run at the desired frequency. Do not run more than every 30 minutes to avoid undue load on the system.  
    - cron: '59 * * * *' # Run Every hour
    # - cron: '1/30 * * * *' # Uncomment to run every 30 minutes
    # - cron: '1/40 * * * *' # Uncomment to run every 40 minutes

permissions:
  id-token: write
  contents: read
  actions: read

env:
  DISPATCH_REF: master
  SELENIUM_TEST_DIR: 'Selenium' # TODO: Update this to the root directory of the Selenium tests
  SELENIUM_RESULTS_DIR: 'Selenium/TestResults' # TODO: Update this to the results output directory
  DOTNET_VERSION: '8.x' # TODO: Specify the .NET SDK version to use
  DOTNET_INSTALL_DIR: './.dotnet'  
  NUGET_CACHE_PATH: '~/.nuget/packages'
  TIMEZONE: America/Denver
  ENVIRONMENTS: '["dev","qa"]' # Define environments as a JSON array
  BROWSER: 'Chrome' # TODO: Set the default browser
  TEST_FILTER: 'TestMethod' # TODO: Define test filter if necessary

jobs:
  nuget-cache:
    runs-on: ubuntu-latest
    
    outputs:
      NUGET_CACHE_KEY: ${{ env.NUGET_CACHE_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.DISPATCH_REF }}
          
      - name: Setup .NET  # TODO: Delete if action runner contains the dotnet version you need.
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        env:
          DOTNET_INSTALL_DIR: ${{ env.DOTNET_INSTALL_DIR }}
    
      - name: Set Cache Keys
        shell: bash
        run: echo "NUGET_CACHE_KEY=nuget-${{ hashFiles('**/*.csproj') }}" >> $GITHUB_ENV
                
      - name: Check for a .NET cache
        id: has-cache
        uses: actions/cache@v4
        with:
          lookup-only: true
          key: ${{ env.NUGET_CACHE_KEY }}
          path: ${{ env.NUGET_CACHE_PATH }}

      - name: Restore Dependencies
        if: steps.has-cache.outputs.cache-hit != 'true'
        shell: bash
        run: dotnet restore ${{ env.SELENIUM_TEST_DIR }}

      - name: Save cache for .NET packages
        if: steps.has-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ env.NUGET_CACHE_KEY }}
          path: ${{ env.NUGET_CACHE_PATH }} 

  build-and-test:
    runs-on: ubuntu-latest
    needs: nuget-cache
    
    strategy:
      matrix:
        environment: ${{ fromJson(env.ENVIRONMENTS) }}
      fail-fast: false

    env:
      ENVIRONMENT: ${{ matrix.environment }}
      NUGET_CACHE_KEY: ${{ needs.nuget-cache.outputs.NUGET_CACHE_KEY }}

    steps:
    

      - name: Setup .NET # TODO: Delete if action runner contains the dotnet version you need.
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Download NuGet Cache
        id: restore-nuget-cache
        uses: actions/cache/restore@v4
        with:
          key: ${{ env.NUGET_CACHE_KEY }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true
          path: ${{ env.NUGET_CACHE_PATH }}

      - name: Build Project
        shell: bash
        run: dotnet build ${{ env.SELENIUM_TEST_DIR }} --configuration Release

      - name: Run Selenium Tests
        working-directory: '${{ env.SELENIUM_TEST_DIR }}'
        shell: bash
        env:
          ENVIRONMENT: ${{ matrix.environment }}
          BROWSER: ${{ env.BROWSER }}
          APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }}
        run: |
          dotnet test --configuration Release \
          --logger "console;verbosity=detailed" \
          --logger "trx;LogFileName=test-results.trx" \
          --filter "${{ env.TEST_FILTER }}"

      - name: Copy Test Results to Results Folder
        if: ${{ always() }}
        continue-on-error: true
        shell: bash
        run: |
          mkdir -p ${{ env.SELENIUM_RESULTS_DIR }}/reports
          cp -r ${{ env.SELENIUM_TEST_DIR }}/TestResults/*.trx ${{ env.SELENIUM_RESULTS_DIR }}/reports

      - name: Upload Selenium Test Report
        if: ${{ failure() }}
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-results
          path: ${{ env.SELENIUM_RESULTS_DIR }}
          retention-days: 5
